 # ----------------------
# 黑名单服务
# ----------------------
upstream blackserver-cluster {
    server 10.194.66.117:8998;
    server 10.194.66.118:8998;

    # 健康检查
    check interval=5000 rise=2 fall=3 timeout=3000 type=http;
    check_http_send "POST /param/server HTTP/1.0\r\n\r\n";
    check_http_expect_alive http_2xx;
}

server {
    listen 8998;

    location / {
        proxy_pass http://blackserver-cluster/;
    }
}
