 # ----------------------
# 传输服务
# ----------------------
upstream transfer-cluster {
    server 10.194.68.230:8182;
    server 10.194.68.231:8182 backup; # 当且仅当所有非backup节点都不可用时，Nginx才会将请求分发到backup节点

    # 健康检查
    check interval=5000 rise=2 fall=3 timeout=3000 default_down=false type=http;
    check_http_send "POST /api/v1/param/query HTTP/1.0\r\n\r\n";
    check_http_expect_alive http_2xx http_4xx;

}

server {
    listen 8182;

    location / {
        proxy_pass http://transfer-cluster/;
    }
}
