version: '3.8'
services:
  nginx:
    image: sawyerlsy/nginx:1.28.0
    container_name: nginx
    restart: always
    network_mode: host # 默认为bridge,这里直接使用宿主机网络栈，避免NAT转换,提高吞吐量和降低延迟
#    ports:
#      - "80:80"
    volumes:
      #- ./html:/usr/share/nginx/html            # 静态文件
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # 主配置文件
      - ./conf/conf.d:/etc/nginx/conf.d              # 子配置文件
      - ./logs:/var/log/nginx                   # 日志
    environment:
      - TZ=Asia/Shanghai                        # 设置时区

# mkdir -p ./logs/{http,stream}
# 检查配置是否正确: docker exec -it nginx nginx -t


# reuseport 是Nginx中一个能显著提升高并发性能的配置项，它的作用是允许多个Nginx工作进程分别创建自己的监听套接字来接受新连接，从而从内核层面减少进程间的锁竞争
# 传统模式（无reuseport）所有工作进程共享一个监听套接字
# reuseport 优化主要解决的是入口流量的高并发接收问题
# 检查reuseport是否起作用: sudo ss -lnp | grep :8848
# 如果启用了 reuseport，每个Worker进程都会有一个独立、完全隔离的监听套接字。ss 命令的输出会像下面这样，显示多个独立的监听条目，每个条目只关联一个进程：
# nginx -T | grep -n -E "client_max_body_size|client_body_buffer_size"
