input {
  beats {
    port => 5046 # 不同的端口对应不同的项目, 使用多管道 (Multiple Pipelines)的方式让配置更加清晰，避免条件地狱
  }
}

filter {

    # 建议：在复杂的Grok解析前加一个条件判断，提升效率
    # 处理日志正文：提取 timestamp, level, thread 等字段.Grok 解析，是 Logstash 中最消耗 CPU 资源的环节
    if [message] =~ /^\d{4}-\d{2}-\d{2}.*---/ {
        grok {
            # 内联正则表达式 (?<field_name>regex)
            match => { "message" => "(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?<level>\w+)\s+\d+\s+---\s+\[(?<thread>[^\]]+)\]\s+(?<class>\S+)\s+(?<method>\S+):(?<line>\d+)\s+:(?<log_body>.*)" }
        }
    }

    # 解析时间戳，替代 promtail 的 timestamp stage
    date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm:ss.SSS" ]
        timezone => "Asia/Shanghai"
        target => "@timestamp" # 解析后的时间戳存储到 @timestamp 字段，这是 ES 的标准时间字段
    }

    # 移除不需要的字段
    mutate {
      remove_field => [ "@version", "agent", "ecs", "input" ]
    }
}

output {

   # 适用data_stream的场景：
   # 真正的时序数据：如应用程序日志、系统指标、网络事件、传感器读数、用户活动追踪等。
   # 只增不改：数据一旦产生就基本不会更新或删除，主要是追加写入和查询。
   # 追求运维自动化：希望最大程度减少人工维护索引、别名和生命周期的工作量，避免因配置错误导致数据写入错误索引或中断

   if [zone] and [app] and [app] == "virtual-station-rebuild" {
       elasticsearch {
            hosts => ["http://10.194.65.135:9200"] # Elasticsearch 地址
            user => "elastic"
            password => "elastic"

            data_stream => "true"
            data_stream_type => "logs" # logs、metrics、synthetics 和 traces 四种类型
            data_stream_dataset => "jiangxi-virtual-station-rebuild" # 使用data_stream的时候,不允许使用变量
            data_stream_namespace => "production"

            #data_stream => "false" # 默认为为true
            #index => "test-%{[zone]}-%{[app]}-%{[env]}-%{+YYYY.MM.dd}" # 使用传统的索引模式,不能以data_stream_type的值开头,比如logs、metrics、synthetics 和 traces,有可能会匹配到默认的logs模板、索引，最终导致出现失败
       }
    }

   if [zone] and [app] and [app] in ["virtual-station-rebuild"] {
       # 条件输出：将 ERROR 级别或包含异常栈的日志发送到 Kafka
       if [level] == "ERROR" or [level] == "error" or "exception" in [tags] or [message] =~ /(ERROR|Exception|at\s+.*\.java)/ {
             kafka {
               # Kafka 集群地址 (根据你的环境修改)
               bootstrap_servers => "10.194.65.133:9092,10.194.65.134:9092,10.194.65.135:9092"
               # 目标 Topic 名称 (建议专门为错误日志创建一个Topic)
               topic_id => "%{[zone]}-%{[app]}-error-logs"
               # 消息格式：推荐使用 JSON，便于后续消费
               codec => json

               # 以下是可选但重要的性能与可靠性配置
               acks => "1"           # all或者1
               compression_type => "snappy"  # 启用压缩，节省带宽
               batch_size => 16384     # 批量发送大小
               linger_ms => 5          # 批量等待时间（毫秒）
             }
       }
   }

   # 开发阶段可以同时输出到标准输出，便于调试,生产环境必须禁用
     #stdout {
     #  codec => rubydebug
     #}

}
