version: "3.8"
services:
  loki:
    container_name: loki
    image: grafana/loki:3.5
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/config.yml -target=all
    volumes:
      - ./config:/etc/loki
      - ./data:/loki # 需要设置777权限
    # 增加内存限制（重要！）
    deploy:
      resources:
        limits:
          memory: 8G
    logging:
      driver: "json-file"
      options:
        max-size: "20m"  # 每个日志文件最大20MB
        max-file: "10"   # 轮转保留10个文件，总计约200MB
        compress: "true" # 启用压缩，节省空间（可选）

# mkdir -p data && chmod 777 data
# docker-compose --compatibility up -d

# 删除指定标签、时间范围的日志
# curl -X POST "http://10.194.68.225:3100/loki/api/v1/delete?query={zone=\"guangdong\",app=\"virtual-station-new\"}&start=1735660800000000000&end=1747324800000000000" -H "Content-Type: application/json"
# http://10.194.65.135:3100/loki/api/v1/delete?query={zone="guangdong",app="virtual-station-new"}&start=2025-01-01T00:00:00Z&end=2025-10-14T07:55:00Z

# 查询删除请求状态
# curl -X GET http://10.194.68.225:3100/loki/api/v1/delete
