version: '3.8'
services:
  nacos1:
    image: sawyerlsy/nacos:v2.5.1-local
    container_name: nacos-node1
    restart: always
    network_mode: host # 默认为bridge,这里直接使用宿主机网络栈，避免NAT转换,提高吞吐量和降低延迟
    environment:
      - TZ=Asia/Shanghai  # 指定时区
      - PREFER_HOST_MODE=ip
      - MODE=cluster  # 单节点部署时将MODE=cluster改成standalone
      - SPRING_DATASOURCE_PLATFORM=gauss # 支持 mysql、gauss、dm
      - DB_HOST=10.194.68.203
      - DB_NAME=nacos
      - DB_PORT=8000
      - DB_USER=root
      - DB_PASSWORD=Gauss_369
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=5Y2B5bm05ZCO55qE5oiR77yM5Lya5oSf6LCi5q2k5Yi75LiN5pS+5byD55qE6Ieq5bex77yb5b2T5oiR6Laz5aSf5aW95pe277yM5LiW55WM5Lya5Li65oiR6K6p6Lev44CC6ICM5q2k5Yi777yM5oiR5q2j5Zyo5Y+Y5b6X5pu05aW977yBU2F3eWVy
      - NACOS_AUTH_IDENTITY_KEY=5Y2B5bm05ZCO55qE5oiR77yM5Lya5oSf6LCi5q2k5Yi75LiN5pS+5byD55qE6Ieq5bex77yb5b2T5oiR6Laz5aSf5aW95pe277yM5LiW55WM5Lya5Li65oiR6K6p6Lev44CC6ICM5q2k5Yi777yM5oiR5q2j5Zyo5Y+Y5b6X5pu05aW977yBU2F3eWVy
      - NACOS_AUTH_IDENTITY_VALUE=5Y2B5bm05ZCO55qE5oiR77yM5Lya5oSf6LCi5q2k5Yi75LiN5pS+5byD55qE6Ieq5bex77yb5b2T5oiR6Laz5aSf5aW95pe277yM5LiW55WM5Lya5Li65oiR6K6p6Lev44CC6ICM5q2k5Yi777yM5oiR5q2j5Zyo5Y+Y5b6X5pu05aW977yBU2F3eWVy
      - NACOS_SERVERS=10.194.68.223:8848,10.194.68.224:8848,10.194.68.225:8848  # 需要和NACOS_SERVER_IP保持一致
      - NACOS_SERVER_IP=10.194.68.223
      - NACOS_APPLICATION_PORT=8848
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - NACOS_NAMING_CLIENT_EXPIRED_TIME=60000
    ports:
      - "8848:8848"   # HTTP
      - "7848:7848"   # Raft
      - "9848:9848"   # Client gRPC
      - "9849:9849"   # Server gRPC
    volumes:
      - ./logs:/home/nacos/logs
