version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: always
    volumes: # data和rules需要设置777权限
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules/:/etc/prometheus/rules/ # 挂载的目录需要设置777权限,否则会提示权限不足
      - ./prometheus/data:/prometheus  # 挂载的目录需要设置777权限,否则会提示权限不足
    ports:
      - "9090:9090"
    networks:
      - monitor
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"

  alertmanager:
    image: prom/alertmanager:v0.28.1
#    volumes: # 根据需要定义具体的规则
#      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    restart: always
    networks:
      - monitor

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: kafka-exporter
    restart: always
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=172.31.0.6:9092"
      - "--kafka.server=172.31.0.7:9092"
      - "--kafka.server=172.31.0.8:9092"
    networks:
      - monitor

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.27.0
    container_name: blackbox-exporter
    restart: always
    ports:
      - "9115:9115"  # Blackbox Exporter 默认端口
    volumes:
      - ./blackbox-exporter:/config  # 挂载配置目录
    command:
      - "--config.file=/config/blackbox.yml"  # 指定配置文件路径
    networks:
      - monitor


networks:
  monitor:
    name: monitor


# mkdir -p prometheus && chmod -R 777 prometheus
# docker-compose --compatibility up -d
