version: '3.8'
services:
  xxl-job-admin:
    image: sawyerlsy/xxl-job-admin:v2.3.0-local
    security_opt:
      - seccomp:unconfined  # 解除线程创建限制
    cap_add:
      - SYS_RESOURCE       # 授予资源控制权限.为容器添加Linux的CAP_SYS_RESOURCE能力（Capability），允许其<200b><200b>突破内核资源限制
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    restart: always
    environment: # springboot会将环境变量名中的 _ 替换为 .，并转换为小写（例如 SPRING_DATASOURCE_URL → spring.datasource.url）,优先级高于application.properties
     - TZ=Asia/Shanghai
     - SPRING_DATASOURCE_URL=jdbc:mysql://10.194.65.131:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=hgrica1@
     - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
     - SERVER_PORT=9999
     - SERVER_SERVLET_CONTEXT_PATH=/dispatch
    ports:
     - "9999:9999"
    volumes:
      - ./logs:/data/applogs  # 持久化日志
    networks:
      - xxl-net

networks:
  xxl-net:
    name: xxl-net
    driver: bridge
