version: '3.1'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    restart: always
    environment:
     - PARAMS=--server.port=9999 --server.servlet.context-path=/dispatch --spring.datasource.url=jdbc:mysql://10.173.234.131:3306/monitor_xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=hgrica1@
    ports:
     - "9999:9999"
#    networks:
#     - app_net
#
#networks:
#  app_net:
#    external: true

