version: "3"
services:
  loki:
    container_name: loki
    image: grafana/loki:3.5
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml -target=all
    volumes:
      - ./config:/etc/loki
      - ./data:/loki # 需要设置777权限
    # 增加内存限制（重要！）
    deploy:
      resources:
        limits:
          memory: 8G

# mkdir -p data
# chmod 777 data
