version: '3.1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    command:
      --authentication_policy=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --explicit_defaults_for_timestamp=true
      --log_bin_trust_function_creators=1
      --max_connections=1000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw@12345
      TZ: Asia/Shanghai # 时区配置亚洲上海
    volumes:
      - ./data:/var/lib/mysql
      #- ./config/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app_net

networks:
  app_net:
    external: true
