# docker-compose --compatibility up -d
version: '3.8'
services:
  redis:
    image: redis:8.2.2-alpine
    container_name: redis-single
    restart: always
    network_mode: host
    volumes:
      - ./data:/data
    command: >
      redis-server
      --port 6379
      --requirepass hgrica1@
      --appendonly yes
      --aof-use-rdb-preamble yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --save 3600 1
      --maxmemory 4GB
      --maxmemory-policy volatile-lru
      --tcp-backlog 10240
      --protected-mode no
      --daemonize no
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4GB'
        reservations:
          cpus: '0.5'
          memory: '2GB'

#    networks:
#      - app_net
#networks:
#  app_net:
#    external: true
