# 7001,7002,7003
# 7004,7005,7006
# 7007,7008,7009
version: '3.8'
services:
  # 实例定义（每台服务器运行3个实例）
  redis-7001:
    image: redis:8.2.2-alpine
    container_name: redis-7001
    restart: always
    network_mode: host
    volumes:
      - ./7001/data:/data
    command: >
      redis-server
      --port 7001
      --requirepass hgrica1@
      --masterauth hgrica1@
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 15000
      --cluster-announce-ip 10.194.68.223
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --appendonly yes
      --aof-use-rdb-preamble yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --save 3600 1
      --maxmemory 4GB
      --maxmemory-policy volatile-lru
      --tcp-backlog 10240
      --cluster-replica-validity-factor 10
      --repl-timeout 60
      --protected-mode no
      --daemonize no
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4GB'

  redis-7002:
    image: redis:8.2.2-alpine
    container_name: redis-7002
    restart: always
    network_mode: host
    volumes:
      - ./7002/data:/data
    command: >
      redis-server
      --port 7002
      --requirepass hgrica1@
      --masterauth hgrica1@
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 15000
      --cluster-announce-ip 10.194.68.223
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --appendonly yes
      --aof-use-rdb-preamble yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --save 3600 1
      --maxmemory 4GB
      --maxmemory-policy volatile-lru
      --tcp-backlog 10240
      --cluster-replica-validity-factor 10
      --repl-timeout 60
      --protected-mode no
      --daemonize no
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4GB'

  redis-7003:
    image: redis:8.2.2-alpine
    container_name: redis-7003
    restart: always
    network_mode: host
    volumes:
      - ./7003/data:/data
    command: >
      redis-server
      --port 7003
      --requirepass hgrica1@
      --masterauth hgrica1@
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 15000
      --cluster-announce-ip 10.194.68.223
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --appendonly yes
      --aof-use-rdb-preamble yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --save 3600 1
      --maxmemory 4GB
      --maxmemory-policy volatile-lru
      --tcp-backlog 10240
      --cluster-replica-validity-factor 10
      --repl-timeout 60
      --protected-mode no
      --daemonize no
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4GB'


# 检查集群状态: cluster nodes
# 检查集群信息: cluster info
