{
 "title": "SpringBoot APM Dashboard（中文版本）",
 "description": "Spring Boot指标面板",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "基础信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "运行时间"
    }
   ]
  },
  {
   "title": "堆内存",
   "type": "stat",
   "description": "最大堆内存，-Xmx设置的参数",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "堆内存"
    }
   ]
  },
  {
   "title": "总请求量",
   "type": "stat",
   "description": "统计请求量，包含当前服务总体请求量以及最近5分钟内的请求量。\n单位：次",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\",instance=~\"$instance\", uri!~\".*actuator.*\"})",
     "legendFormat": "总请求量"
    }
   ]
  },
  {
   "title": "进程打开文件数",
   "type": "timeseries",
   "description": "process_files_max_files：代表一个进程可以打开的最大文件描述符数量。在 Linux 中，每个进程都有一个文件描述符表，用于跟踪该进程打开的所有文件、套接字等。默认情况下，这个数量是有限的，超过显示会报错（too many open files）。\nprocess_files_open_files：表示当前进程已经打开的文件描述符数量。\n可以通过ulimit -a查看系统配置的最大文件描述符数量（open files）。可以在/etc/security/limits.conf修改",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "description": "服务启动的时间",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000",
     "legendFormat": "启动时间"
    }
   ]
  },
  {
   "title": "非堆内存",
   "type": "stat",
   "description": "非堆内存大小，方法区（Method Area）与 Java 堆一样，是各个线程共享的内存区域，它用于存储\n已被虚拟机加载的类型信息、常量、静态变量、即时编译器编译后的代码缓存等数据。\n虽然《Java 虚拟机规范》中把方法区描述为堆的一个逻辑部分，但是它却有一个别名叫\n作“非堆”（Non-Heap），目的是与 Java 堆区分开来。",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "非堆内存"
    }
   ]
  },
  {
   "title": "请求量【近5分钟】",
   "type": "stat",
   "description": "统计请求量，包含当前服务总体请求量以及最近5分钟内的请求量。\n单位：次",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\",instance=~\"$instance\", uri!~\".*actuator.*\"}[5m]) )",
     "legendFormat": "请求量【近5分钟】"
    }
   ]
  },
  {
   "title": "请求QPS",
   "type": "timeseries",
   "description": "QPS（每秒请求数）是指单位时间内的请求次数，是一个衡量系统吞吐量的重要指标。应用服务的请求QPS指的是在单位时间内，应用服务处理的请求数量。它可以帮助评估系统的性能，以及请求处理能力是否足够，是否需要对系统进行优化或扩容。\n\n优化应用服务请求QPS（每秒请求数）的方法可能包括：\n\n减少请求时间：通过优化代码，缩短请求执行时间，从而提高每秒请求数。\n\n增加服务器性能：通过升级服务器的配置，提高服务器的处理能力，从而提高每秒请求数。\n\n分布式系统：通过使用分布式系统，将请求分配到多台服务器上，从而提高每秒请求数。\n\n缓存：通过使用缓存，减少请求的数据处理时间，从而提高每秒请求数。\n\n减少请求数量：通过消除不必要的请求，减少请求数量，从而提高每秒请求数。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m]))",
     "legendFormat": "当前数据"
    }
   ]
  },
  {
   "title": "请求QPS(TOP5)",
   "type": "timeseries",
   "description": "QPS（每秒请求数）是指单位时间内的请求次数，是一个衡量系统吞吐量的重要指标。应用服务的请求QPS指的是在单位时间内，应用服务处理的请求数量。它可以帮助评估系统的性能，以及请求处理能力是否足够，是否需要对系统进行优化或扩容。\n\n优化应用服务请求QPS（每秒请求数）的方法可能包括：\n\n减少请求时间：通过优化代码，缩短请求执行时间，从而提高每秒请求数。\n\n增加服务器性能：通过升级服务器的配置，提高服务器的处理能力，从而提高每秒请求数。\n\n分布式系统：通过使用分布式系统，将请求分配到多台服务器上，从而提高每秒请求数。\n\n缓存：通过使用缓存，减少请求的数据处理时间，从而提高每秒请求数。\n\n减少请求数量：通过消除不必要的请求，减少请求数量，从而提高每秒请求数。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(uri, method) (rate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])))",
     "legendFormat": "{{method}}-{{uri}}"
    }
   ]
  },
  {
   "title": "内存使用率（%）",
   "type": "timeseries",
   "description": "内存使用率\n\n堆内存使用率正常指标范围参考：\n\nJava应用会有一定的内存占用，但内存使用率应该保持在合理范围内。通常情况下，70-80%的内存使用率是可以接受的。\n\n如果内存使用率长期接近或达到100%，可能存在内存泄漏问题或内存不足。",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "Heap Memory Usage（堆内存使用率）"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "Non-Heap Memory Usage（非堆内存使用率）"
    }
   ]
  },
  {
   "title": "磁盘使用率（%）",
   "type": "timeseries",
   "description": "应用所在磁盘使用率\n\n正常指标范围参考：\n\n这个指标其实和CPU数和内存都没啥关系，一般来说磁盘超过80%就要报警了。有的日志比较多的应用，可能在60%左右就需要来看了。\n\n一般为了让磁盘的利用率维持在一定水位上，机器都需要配置日志的自动清理。\t",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(disk_total_bytes{application=\"$application\",instance=~\"$instance\"} - disk_free_bytes{application=\"$application\", instance=~\"$instance\"})/(disk_total_bytes{application=\"$application\",instance=~\"$instance\"})",
     "legendFormat": "{{path}}-磁盘使用率"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "description": "正常指标范围参考：\n\n在空闲或轻负载情况下，CPU使用率应较低，通常在0-30%左右。\n\n在中等负载下，使用率可能在30-70%。\n\n高负载或高性能需求的情况下，CPU使用率可能会更高，但是最好不要长期超过80%。一般建议控制在70%以下。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage（系统CPU使用率）"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage（进程cpu使用率）"
    }
   ]
  },
  {
   "title": "Load average（系统负载）",
   "type": "timeseries",
   "description": "system_load_average_1m 通常指的是系统在过去1分钟内的平均负载（Load Average）。在Linux系统中，你可以使用多种命令来查看当前的平均负载，包括 uptime、top以及查看 /proc/loadavg 文件。load average后边会有三个值，分别代表1分钟，5分钟，15分钟负载情况。\n\n正常指标范围参考：\n对于4核CPU，理想的系统负载值应低于4。超过这个值可能意味着过载。一般来说应该维持在50%以下，也就是2以下。\n如果长时间超过75%，也就是3的话，那么就需要进行排查看看是不是存在问题了。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m](1分钟系统负载)"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size（CPU核数）"
    }
   ]
  },
  {
   "title": "JVM内存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "timeseries",
   "description": "在JVM（Java Virtual Machine）的性能监控和诊断中，jvm_threads_daemon_threads、jvm_threads_live_threads 和 jvm_threads_peak_threads 是常见的度量指标，用于描述JVM中线程的状态和数量。下面我将逐一解释这些指标：\n\njvm_threads_daemon_threads\n定义：当前JVM中守护线程（Daemon Threads）的数量。\n解释：守护线程是一种特殊的线程，它在其他所有非守护线程结束后自动结束。通常，守护线程用于执行后台任务，如垃圾回收线程就是一个守护线程。如果JVM中只剩下守护线程在运行，那么JVM会退出。\njvm_threads_live_threads\n定义：当前JVM中活动线程（Live Threads）的数量。\n解释：活动线程是指已经启动但尚未结束的线程。这个数字通常包括了应用代码创建的线程，以及JVM内部使用的线程（如垃圾回收线程）。这个指标可以帮助你了解当前JVM的线程使用情况，如果这个数字持续很高，可能意味着你的应用正在创建大量的线程，这可能会导致性能问题或资源耗尽。\njvm_threads_peak_threads\n定义：从JVM启动到当前时间，活动线程数量的峰值。\n解释：这个指标记录了JVM在其生命周期中活动线程数量的最大值。通过比较jvm_threads_live_threads和jvm_threads_peak_threads，你可以了解你的应用在何时达到了线程使用的峰值，并据此进行性能调优或资源规划。",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon（守护线程）"
    },
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Live（活动线程）"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak(活动线程峰值)"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "description": "jvm_gc_memory_allocated_bytes_total 是一个 JVM 指标，用于记录自 JVM 启动以来分配的总内存大小。它是一个累积计数器，随着时间的推移，其值会不断增加，因为 JVM 会不断分配内存。\njvm_gc_memory_promoted_bytes_total 则记录了从新生代（Young Generation）晋升到老年代（Old Generation）的内存大小总和。它反映了对象在垃圾回收过程中的存活率。\n这两个指标都可以帮助你了解 JVM 中内存的使用情况和对象的生命周期。通过监控这些指标，你可以观察到应用程序中内存的分配和晋升情况，并根据需要调整内存分配和垃圾回收策略，以优化应用程序的性能和内存使用效率。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "JVM-GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "吞吐量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP状态码",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"5..\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "5xx - Server Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"4..\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "4xx - Client Errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"3..\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "3xx - Redirections"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"2..\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "2xx - Success"
    }
   ]
  },
  {
   "title": "HTTP请求数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback日志",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}